Warning: truncated output (original token count: 90612)
Total output lines: 13405

/* eslint-disable */
// This file is generated by scripts/generateLocaleInterface.ts
// Do not edit this file directly.
import { type ILocale, type ParameterizedString } from "../types.js";
export interface Locale extends ILocale {
    /**
     * 日本語
     */
    "_lang_": string;
    /**
     * ノートでつながるネットワーク
     */
    "headlineMisskey": string;
    /**
     * ようこそ！Misskeyは、オープンソースの分散型マイクロブログサービスです。
     * 「ノート」を作成して、いま起こっていることを共有したり、あなたについて皆に発信しよう📡
     * 「リアクション」機能で、皆のノートに素早く反応を追加することもできます👍
     * 新しい世界を探検しよう🚀
     */
    "introMisskey": string;
    /**
     * {name}は、オープンソースのプラットフォーム<b>Misskey</b>のサーバーのひとつです。
     */
    "poweredByMisskeyDescription": ParameterizedString<"name">;
    /**
     * {month}月 {day}日
     */
    "monthAndDay": ParameterizedString<"month" | "day">;
    /**
     * 検索
     */
    "search": string;
    /**
     * リセット
     */
    "reset": string;
    /**
     * 通知
     */
    "notifications": string;
    /**
     * ユーザー名
     */
    "username": string;
    /**
     * パスワード
     */
    "password": string;
    /**
     * 初期設定開始用パスワード
     */
    "initialPasswordForSetup": string;
    /**
     * 初期設定開始用のパスワードが違います。
     */
    "initialPasswordIsIncorrect": string;
    /**
     * Misskeyを自分でインストールした場合は、設定ファイルに入力したパスワードを使用してください。
     * Misskeyのホスティングサービスなどを使用している場合は、提供されたパスワードを使用してください。
     * パスワードを設定していない場合は、空欄にしたまま続行してください。
     */
    "initialPasswordForSetupDescription": string;
    /**
     * パスワードを忘れた
     */
    "forgotPassword": string;
    /**
     * 連合に照会中
     */
    "fetchingAsApObject": string;
    /**
     * OK
     */
    "ok": string;
    /**
     * わかった
     */
    "gotIt": string;
    /**
     * キャンセル
     */
    "cancel": string;
    /**
     * やめておく
     */
    "noThankYou": string;
    /**
     * ユーザー名を入力
     */
    "enterUsername": string;
    /**
     * {user}がリノート
     */
    "renotedBy": ParameterizedString<"user">;
    /**
     * ノートはありません
     */
    "noNotes": string;
    /**
     * 通知はありません
     */
    "noNotifications": string;
    /**
     * サーバー
     */
    "instance": string;
    /**
     * 設定
     */
    "settings": string;
    /**
     * 通知の設定
     */
    "notificationSettings": string;
    /**
     * 基本設定
     */
    "basicSettings": string;
    /**
     * その他の設定
     */
    "otherSettings": string;
    /**
     * ウィンドウで開く
     */
    "openInWindow": string;
    /**
     * プロフィール
     */
    "profile": string;
    /**
     * タイムライン
     */
    "timeline": string;
    /**
     * 自己紹介はありません
     */
    "noAccountDescription": string;
    /**
     * ログイン
     */
    "login": string;
    /**
     * ログイン中
     */
    "loggingIn": string;
    /**
     * ログアウト
     */
    "logout": string;
    /**
     * 新規登録
     */
    "signup": string;
    /**
     * アップロード中
     */
    "uploading": string;
    /**
     * 保存
     */
    "save": string;
    /**
     * ユーザー
     */
    "users": string;
    /**
     * ユーザーを追加
     */
    "addUser": string;
    /**
     * お気に入り
     */
    "favorite": string;
    /**
     * お気に入り
     */
    "favorites": string;
    /**
     * お気に入り解除
     */
    "unfavorite": string;
    /**
     * お気に入りに登録しました。
     */
    "favorited": string;
    /**
     * 既にお気に入りに登録されています。
     */
    "alreadyFavorited": string;
    /**
     * お気に入りに登録できませんでした。
     */
    "cantFavorite": string;
    /**
     * ピン留め
     */
    "pin": string;
    /**
     * ピン留め解除
     */
    "unpin": string;
    /**
     * 内容をコピー
     */
    "copyContent": string;
    /**
     * リンクをコピー
     */
    "copyLink": string;
    /**
     * リモートのリンクをコピー
     */
    "copyRemoteLink": string;
    /**
     * リノートのリンクをコピー
     */
    "copyLinkRenote": string;
    /**
     * 削除
     */
    "delete": string;
    /**
     * 削除して編集
     */
    "deleteAndEdit": string;
    /**
     * このノートを削除してもう一度編集しますか？このノートへのリアクション、リノート、返信も全て削除されます。
     */
    "deleteAndEditConfirm": string;
    /**
     * リストに追加
     */
    "addToList": string;
    /**
     * アンテナに追加
     */
    "addToAntenna": string;
    /**
     * メッセージを送信
     */
    "sendMessage": string;
    /**
     * RSSをコピー
     */
    "copyRSS": string;
    /**
     * ユーザー名をコピー
     */
    "copyUsername": string;
    /**
     * ユーザーIDをコピー
     */
    "copyUserId": string;
    /**
     * ノートIDをコピー
     */
    "copyNoteId": string;
    /**
     * ファイルIDをコピー
     */
    "copyFileId": string;
    /**
     * フォルダーIDをコピー
     */
    "copyFolderId": string;
    /**
     * プロフィールURLをコピー
     */
    "copyProfileUrl": string;
    /**
     * ユーザーを検索
     */
    "searchUser": string;
    /**
     * ユーザーのノートを検索
     */
    "searchThisUsersNotes": string;
    /**
     * 返信
     */
    "reply": string;
    /**
     * もっと見る
     */
    "loadMore": string;
    /**
     * もっと見る
     */
    "showMore": string;
    /**
     * 閉じる
     */
    "showLess": string;
    /**
     * フォローされました
     */
    "youGotNewFollower": string;
    /**
     * フォローリクエストされました
     */
    "receiveFollowRequest": string;
    /**
     * フォローが承認されました
     */
    "followRequestAccepted": string;
    /**
     * メンション
     */
    "mention": string;
    /**
     * メンション
     */
    "mentions": string;
    /**
     * 指名
     */
    "directNotes": string;
    /**
     * インポートとエクスポート
     */
    "importAndExport": string;
    /**
     * インポート
     */
    "import": string;
    /**
     * エクスポート
     */
    "export": string;
    /**
     * ファイル
     */
    "files": string;
    /**
     * ダウンロード
     */
    "download": string;
    /**
     * ファイル「{name}」を削除しますか？このファイルを使用した一部のコンテンツも削除されます。
     */
    "driveFileDeleteConfirm": ParameterizedString<"name">;
    /**
     * {name}のフォローを解除しますか？
     */
    "unfollowConfirm": ParameterizedString<"name">;
    /**
     * {name}へのフォロー申請をキャンセルしますか？
     */
    "cancelFollowRequestConfirm": ParameterizedString<"name">;
    /**
     * {name}からのフォロー申請を拒否しますか？
     */
    "rejectFollowRequestConfirm": ParameterizedString<"name">;
    /**
     * エクスポートをリクエストしました。これには時間がかかる場合があります。エクスポートが終わると、「ドライブ」に追加されます。
     */
    "exportRequested": string;
    /**
     * インポートをリクエストしました。これには時間がかかる場合があります。
     */
    "importRequested": string;
    /**
     * リスト
     */
    "lists": string;
    /**
     * リストはありません
     */
    "noLists": string;
    /**
     * ノート
     */
    "note": string;
    /**
     * ノート
     */
    "notes": string;
    /**
     * フォロー
     */
    "following": string;
    /**
     * フォロワー
     */
    "followers": string;
    /**
     * フォローされています
     */
    "followsYou": string;
    /**
     * リスト作成
     */
    "createList": string;
    /**
     * リストの管理
     */
    "manageLists": string;
    /**
     * エラー
     */
    "error": string;
    /**
     * 問題が発生しました
     */
    "somethingHappened": string;
    /**
     * 再試行
     */
    "retry": string;
    /**
     * ページの読み込みに失敗しました。
     */
    "pageLoadError": string;
    /**
     * これは通常、ネットワークまたはブラウザキャッシュが原因です。キャッシュをクリアするか、しばらく待ってから再度試してください。
     */
    "pageLoadErrorDescription": string;
    /**
     * サーバーの応答がありません。しばらく待ってから再度試してください。
     */
    "serverIsDead": string;
    /**
     * このページを表示するためには、リロードして新しいバージョンのクライアントをご利用ください。
     */
    "youShouldUpgradeClient": string;
    /**
     * リスト名を入力
     */
    "enterListName": string;
    /**
     * プライバシー
     */
    "privacy": string;
    /**
     * フォローを承認制にする
     */
    "makeFollowManuallyApprove": string;
    /**
     * デフォルトの公開範囲
     */
    "defaultNoteVisibility": string;
    /**
     * フォロー
     */
    "follow": string;
    /**
     * フォロー申請
     */
    "followRequest": string;
    /**
     * フォロー申請
     */
    "followRequests": string;
    /**
     * フォロー解除
     */
    "unfollow": string;
    /**
     * フォロー許可待ち
     */
    "followRequestPending": string;
    /**
     * 絵文字を入力
     */
    "enterEmoji": string;
    /**
     * リノート
     */
    "renote": string;
    /**
     * リノート解除
     */
    "unrenote": string;
    /**
     * リノートしました。
     */
    "renoted": string;
    /**
     * {name} にリノートしました。
     */
    "renotedToX": ParameterizedString<"name">;
    /**
     * この投稿はリノートできません。
     */
    "cantRenote": string;
    /**
     * リノートをリノートすることはできません。
     */
    "cantReRenote": string;
    /**
     * 引用
     */
    "quote": string;
    /**
     * チャンネル内リノート
     */
    "inChannelRenote": string;
    /**
     * チャンネル内引用
     */
    "inChannelQuote": string;
    /**
     * チャンネルにリノート
     */
    "renoteToChannel": string;
    /**
     * 他のチャンネルにリノート
     */
    "renoteToOtherChannel": string;
    /**
     * ピン留めされたノート
     */
    "pinnedNote": string;
    /**
     * ピン留め
     */
    "pinned": string;
    /**
     * あなた
     */
    "you": string;
    /**
     * クリックして表示
     */
    "clickToShow": string;
    /**
     * センシティブ
     */
    "sensitive": string;
    /**
     * 追加
     */
    "add": string;
    /**
     * リアクション
     */
    "reaction": string;
    /**
     * リアクション
     */
    "reactions": string;
    /**
     * 絵文字ピッカー
     */
    "emojiPicker": string;
    /**
     * リアクション時にピン留め表示する絵文字を設定できます
     */
    "pinnedEmojisForReactionSettingDescription": string;
    /**
     * 絵文字入力時にピン留め表示する絵文字を設定できます
     */
    "pinnedEmojisSettingDescription": string;
    /**
     * ピッカーの表示
     */
    "emojiPickerDisplay": string;
    /**
     * リアクション設定から上書きする
     */
    "overwriteFromPinnedEmojisForReaction": string;
    /**
     * 全般設定から上書きする
     */
    "overwriteFromPinnedEmojis": string;
    /**
     * ドラッグして並び替え、クリックして削除、＋を押して追加します。
     */
    "reactionSettingDescription2": string;
    /**
     * 公開範囲を記憶する
     */
    "rememberNoteVisibility": string;
    /**
     * 添付取り消し
     */
    "attachCancel": string;
    /**
     * ファイルを削除
     */
    "deleteFile": string;
    /**
     * センシティブとして設定
     */
    "markAsSensitive": string;
    /**
     * センシティブを解除する
     */
    "unmarkAsSensitive": string;
    /**
     * ファイル名を入力
     */
    "enterFileName": string;
    /**
     * ミュート
     */
    "mute": string;
    /**
     * ミュート解除
     */
    "unmute": string;
    /**
     * リノートをミュート
     */
    "renoteMute": string;
    /**
     * リノートのミュートを解除
     */
    "renoteUnmute": string;
    /**
     * ブロック
     */
    "block": string;
    /**
     * ブロック解除
     */
    "unblock": string;
    /**
     * 凍結
     */
    "suspend": string;
    /**
     * 解凍
     */
    "unsuspend": string;
    /**
     * ブロックしますか？
     */
    "blockConfirm": string;
    /**
     * ブロック解除しますか？
     */
    "unblockConfirm": string;
    /**
     * 凍結しますか？
     */
    "suspendConfirm": string;
    /**
     * 解凍しますか？
     */
    "unsuspendConfirm": string;
    /**
     * リストを選択
     */
    "selectList": string;
    /**
     * リストを編集
     */
    "editList": string;
    /**
     * チャンネルを選択
     */
    "selectChannel": string;
    /**
     * アンテナを選択
     */
    "selectAntenna": string;
    /**
     * アンテナを編集
     */
    "editAntenna": string;
    /**
     * アンテナを作成
     */
    "createAntenna": string;
    /**
     * ウィジェットを選択
     */
    "selectWidget": string;
    /**
     * ウィジェットを編集
     */
    "editWidgets": string;
    /**
     * 編集を終了
     */
    "editWidgetsExit": string;
    /**
     * カスタム絵文字
     */
    "customEmojis": string;
    /**
     * 絵文字
     */
    "emoji": string;
    /**
     * 絵文字
     */
    "emojis": string;
    /**
     * 絵文字名
     */
    "emojiName": string;
    /**
     * 絵文字画像URL
     */
    "emojiUrl": string;
    /**
     * 絵文字を追加
     */
    "addEmoji": string;
    /**
     * おすすめ設定
     */
    "settingGuide": string;
    /**
     * リモートのファイルをキャッシュする
     */
    "cacheRemoteFiles": string;
    /**
     * この設定を有効にすると、リモートファイルをこのサーバーのストレージにキャッシュするようになります。画像の表示が高速になりますが、サーバーのストレージを多く消費します。リモートユーザーがどれほどキャッシュを保持するかは、ロールによるドライブ容量制限によって決定されます。この制限を超えた場合、古いファイルからキャッシュが削除されリンクになります。この設定が無効の場合、リモートのファイルを最初からリンクとして保持します。
     */
    "cacheRemoteFilesDescription": string;
    /**
     * ファイル管理の🗑️ボタンで全てのキャッシュを削除できます。
     */
    "youCanCleanRemoteFilesCache": string;
    /**
     * リモートのセンシティブなファイルをキャッシュする
     */
    "cacheRemoteSensitiveFiles": string;
    /**
     * この設定を無効にすると、リモートのセンシティブなファイルはキャッシュせず直リンクするようになります。
     */
    "cacheRemoteSensitiveFilesDescription": string;
    /**
     * Botとして設定
     */
    "flagAsBot": string;
    /**
     * このアカウントがプログラムによって運用される場合は、このフラグをオンにします。オンにすると、反応の連鎖を防ぐためのフラグとして他の開発者に役立ったり、Misskeyのシステム上での扱いがBotに合ったものになります。
     */
    "flagAsBotDescription": string;
    /**
     * にゃああああああああああああああ！！！！！！！！！！！！
     */
    "flagAsCat": string;
    /**
     * にゃにゃにゃ？？
     */
    "flagAsCatDescription": string;
    /**
     * タイムラインにノートへの返信を表示する
     */
    "flagShowTimelineReplies": string;
    /**
     * オンにすると、タイムラインにユーザーのノート以外にもそのユーザーの他のノートへの返信を表示します。
     */
    "flagShowTimelineRepliesDescription": string;
    /**
     * フォロー中ユーザーからのフォロー申請を自動承認
     */
    "autoAcceptFollowed": string;
    /**
     * アカウントを追加
     */
    "addAccount": string;
    /**
     * アカウントリストの情報を更新
     */
    "reloadAccountsList": string;
    /**
     * ログインに失敗しました
     */
    "loginFailed": string;
    /**
     * リモートで表示
     */
    "showOnRemote": string;
    /**
     * リモートで続行
     */
    "continueOnRemote": string;
    /**
     * Misskey Hubからサーバーを選択
     */
    "chooseServerOnMisskeyHub": string;
    /**
     * サーバーのドメインを直接指定
     */
    "specifyServerHost": string;
    /**
     * ドメインを入力してください
     */
    "inputHostName": string;
    /**
     * 全般
     */
    "general": string;
    /**
     * 壁紙
     */
    "wallpaper": string;
    /**
     * 壁紙を設定
     */
    "setWallpaper": string;
    /**
     * 壁紙を削除
     */
    "removeWallpaper": string;
    /**
     * 検索: {q}
     */
    "searchWith": ParameterizedString<"q">;
    /**
     * リストがありません
     */
    "youHaveNoLists": string;
    /**
     * {name}をフォローしますか？
     */
    "followConfirm": ParameterizedString<"name">;
    /**
     * プロキシアカウント
     */
    "proxyAccount": string;
    /**
     * プロキシアカウントは、特定の条件下でユーザーのリモートフォローを代行するアカウントです。例えば、ユーザーがリモートユーザーをリストに入れたとき、リストに入れられたユーザーを誰もフォローしていないとアクティビティがサーバーに配達されないため、代わりにプロキシアカウントがフォローするようにします。
     */
    "proxyAccountDescription": string;
    /**
     * ホスト
     */
    "host": string;
    /**
     * 自分を選択
     */
    "selectSelf": string;
    /**
     * ユーザーを選択
     */
    "selectUser": string;
    /**
     * 宛先
     */
    "recipient": string;
    /**
     * 注釈
     */
    "annotation": string;
    /**
     * 連合
     */
    "federation": string;
    /**
     * サーバー
     */
    "instances": string;
    /**
     * 初観測
     */
    "registeredAt": string;
    /**
     * 直近のリクエスト受信
     */
    "latestRequestReceivedAt": string;
    /**
     * 直近のステータス
     */
    "latestStatus": string;
    /**
     * ストレージ使用量
     */
    "storage…80612 tokens truncated…tring;
        /**
         * このウィザードで簡単に最適なサーバーの設定が行えます。
         */
        "youCanEasilyConfigureOptimalServerSettingsWithThisWizard": string;
        /**
         * ここでの設定は、あとからでも変更できます。
         */
        "settingsYouMakeHereCanBeChangedLater": string;
        /**
         * Misskeyをどのように使いますか？
         */
        "howWillYouUseMisskey": string;
        "_use": {
            /**
             * お一人様サーバー
             */
            "single": string;
            /**
             * 自分専用のサーバーとして、一人で使う
             */
            "single_description": string;
            /**
             * お一人様サーバーとして運用する場合でも、アカウントは必要に応じて複数作成可能です。
             */
            "single_youCanCreateMultipleAccounts": string;
            /**
             * グループサーバー
             */
            "group": string;
            /**
             * 信頼できる他の利用者を招待して、複数人で使う
             */
            "group_description": string;
            /**
             * オープンサーバー
             */
            "open": string;
            /**
             * 不特定多数の利用者を受け入れる運営を行う
             */
            "open_description": string;
        };
        /**
         * 不特定多数の利用者を受け入れることはリスクが伴います。トラブルに対処できるよう、確実なモデレーション体制で運営することを推奨します。
         */
        "openServerAdvice": string;
        /**
         * 自サーバーがスパムの踏み台にならないように、reCAPTCHAといったアンチボット機能を有効にするなど、セキュリティについても細心の注意が必要です。
         */
        "openServerAntiSpamAdvice": string;
        /**
         * どれくらいの人数を想定していますか？
         */
        "howManyUsersDoYouExpect": string;
        "_scale": {
            /**
             * 100人以下 (小規模)
             */
            "small": string;
            /**
             * 100人以上1000人以下 (中規模)
             */
            "medium": string;
            /**
             * 1000人以上 (大規模)
             */
            "large": string;
        };
        /**
         * 大規模なサーバーでは、ロードバランシングやデータベースのレプリケーションなど、高度なインフラストラクチャーの知識が必要になる場合があります。
         */
        "largeScaleServerAdvice": string;
        /**
         * Fediverseと接続しますか？
         */
        "doYouConnectToFediverse": string;
        /**
         * 分散型サーバーで構成されるネットワーク(Fediverse)に接続すると、他のサーバーと相互にコンテンツのやり取りが可能です。
         */
        "doYouConnectToFediverse_description1": string;
        /**
         * Fediverseと接続することは「連合」とも呼ばれます。
         */
        "doYouConnectToFediverse_description2": string;
        /**
         * 連合可能なサーバーの指定など、高度な設定も後ほど可能です。
         */
        "youCanConfigureMoreFederationSettingsLater": string;
        /**
         * リモートコンテンツの自動クリーニング
         */
        "remoteContentsCleaning": string;
        /**
         * 連合を行うと、継続して多くのコンテンツを受信します。自動クリーニングを有効にすると、一定期間経過したリモートコンテンツを自動でサーバーから削除し、ストレージを節約できます。
         */
        "remoteContentsCleaning_description": string;
        /**
         * 管理者情報
         */
        "adminInfo": string;
        /**
         * 問い合わせを受け付けるために使用される管理者情報を設定します。
         */
        "adminInfo_description": string;
        /**
         * オープンサーバー、または連合がオンの場合は必ず入力が必要です。
         */
        "adminInfo_mustBeFilled": string;
        /**
         * 以下の設定が推奨されます
         */
        "followingSettingsAreRecommended": string;
        /**
         * この設定を適用
         */
        "applyTheseSettings": string;
        /**
         * 設定をスキップ
         */
        "skipSettings": string;
        /**
         * 設定が完了しました！
         */
        "settingsCompleted": string;
        /**
         * お疲れ様でした。準備が整ったので、さっそくサーバーの使用を開始できます。
         */
        "settingsCompleted_description": string;
        /**
         * 詳細なサーバー設定は、「コントロールパネル」から行えます。
         */
        "settingsCompleted_description2": string;
        /**
         * 寄付のお願い
         */
        "donationRequest": string;
        "_donationRequest": {
            /**
             * Misskeyは有志によって開発されている無料のソフトウェアです。
             */
            "text1": string;
            /**
             * 今後も開発を続けられるように、よろしければぜひカンパをお願いいたします。
             */
            "text2": string;
            /**
             * 支援者向け特典もあります！
             */
            "text3": string;
        };
    };
    "_uploader": {
        /**
         * 画像の編集
         */
        "editImage": string;
        /**
         * {x}に圧縮
         */
        "compressedToX": ParameterizedString<"x">;
        /**
         * {x}%節約
         */
        "savedXPercent": ParameterizedString<"x">;
        /**
         * アップロードされていないファイルがありますが、中止しますか？
         */
        "abortConfirm": string;
        /**
         * アップロードされていないファイルがありますが、完了しますか？
         */
        "doneConfirm": string;
        /**
         * アップロード可能な最大ファイルサイズは{x}です。
         */
        "maxFileSizeIsX": ParameterizedString<"x">;
        /**
         * アップロード可能なファイル種別
         */
        "allowedTypes": string;
        /**
         * ファイルはまだアップロードされていません。このダイアログで、アップロード前の確認・リネーム・圧縮・クロッピングなどが行えます。準備が出来たら、「アップロード」ボタンを押してアップロードを開始できます。
         */
        "tip": string;
    };
    "_clientPerformanceIssueTip": {
        /**
         * バッテリー消費が多いと感じたら
         */
        "title": string;
        /**
         * アドブロッカーを無効にしてください
         */
        "makeSureDisabledAdBlocker": string;
        /**
         * アドブロッカーはパフォーマンスに影響を及ぼすことがあります。OSの機能やブラウザの機能・アドオンなどでアドブロッカーが有効になっていないか確認してください。
         */
        "makeSureDisabledAdBlocker_description": string;
        /**
         * カスタムCSSを無効にしてください
         */
        "makeSureDisabledCustomCss": string;
        /**
         * スタイルを上書きするとパフォーマンスに影響を及ぼすことがあります。カスタムCSSや、スタイルを上書きする拡張機能が有効になっていないか確認してください。
         */
        "makeSureDisabledCustomCss_description": string;
        /**
         * 拡張機能を無効にしてください
         */
        "makeSureDisabledAddons": string;
        /**
         * 一部の拡張機能はクライアントの動作に干渉しパフォーマンスに影響を及ぼすことがあります。ブラウザの拡張機能を無効にして改善するか確認してください。
         */
        "makeSureDisabledAddons_description": string;
    };
    "_clip": {
        /**
         * クリップは、ノートをまとめることができる機能です。
         */
        "tip": string;
    };
    "_userLists": {
        /**
         * 任意のユーザーが含まれるリストを作成できます。作成したリストはタイムラインとして表示可能です。
         */
        "tip": string;
    };
    /**
     * ウォーターマーク
     */
    "watermark": string;
    /**
     * デフォルトのプリセット
     */
    "defaultPreset": string;
    "_watermarkEditor": {
        /**
         * 画像にクレジット情報などのウォーターマークを追加できます。
         */
        "tip": string;
        /**
         * 保存せずに終了しますか？
         */
        "quitWithoutSaveConfirm": string;
        /**
         * このファイルは対応していません
         */
        "driveFileTypeWarn": string;
        /**
         * 画像ファイルを選択してください
         */
        "driveFileTypeWarnDescription": string;
        /**
         * ウォーターマークの編集
         */
        "title": string;
        /**
         * 全体に被せる
         */
        "cover": string;
        /**
         * 敷き詰める
         */
        "repeat": string;
        /**
         * 回転時はみ出ないように調整する
         */
        "preserveBoundingRect": string;
        /**
         * 不透明度
         */
        "opacity": string;
        /**
         * サイズ
         */
        "scale": string;
        /**
         * テキスト
         */
        "text": string;
        /**
         * 二次元コード
         */
        "qr": string;
        /**
         * 位置
         */
        "position": string;
        /**
         * マージン
         */
        "margin": string;
        /**
         * タイプ
         */
        "type": string;
        /**
         * 画像
         */
        "image": string;
        /**
         * 高度
         */
        "advanced": string;
        /**
         * 角度
         */
        "angle": string;
        /**
         * ストライプ
         */
        "stripe": string;
        /**
         * ラインの幅
         */
        "stripeWidth": string;
        /**
         * ラインの数
         */
        "stripeFrequency": string;
        /**
         * ポルカドット
         */
        "polkadot": string;
        /**
         * チェッカー
         */
        "checker": string;
        /**
         * メインドットの不透明度
         */
        "polkadotMainDotOpacity": string;
        /**
         * メインドットの大きさ
         */
        "polkadotMainDotRadius": string;
        /**
         * サブドットの不透明度
         */
        "polkadotSubDotOpacity": string;
        /**
         * サブドットの大きさ
         */
        "polkadotSubDotRadius": string;
        /**
         * サブドットの数
         */
        "polkadotSubDotDivisions": string;
        /**
         * 空欄にするとアカウントのURLになります
         */
        "leaveBlankToAccountUrl": string;
        /**
         * 画像の読み込みに失敗しました
         */
        "failedToLoadImage": string;
    };
    "_imageEffector": {
        /**
         * エフェクト
         */
        "title": string;
        /**
         * エフェクトを追加
         */
        "addEffect": string;
        /**
         * 変更を破棄して終了しますか？
         */
        "discardChangesConfirm": string;
        /**
         * 画像の読み込みに失敗しました
         */
        "failedToLoadImage": string;
        "_fxs": {
            /**
             * 色収差
             */
            "chromaticAberration": string;
            /**
             * グリッチ
             */
            "glitch": string;
            /**
             * ミラー
             */
            "mirror": string;
            /**
             * 色の反転
             */
            "invert": string;
            /**
             * 白黒
             */
            "grayscale": string;
            /**
             * ぼかし
             */
            "blur": string;
            /**
             * モザイク
             */
            "pixelate": string;
            /**
             * 色調補正
             */
            "colorAdjust": string;
            /**
             * 色の圧縮
             */
            "colorClamp": string;
            /**
             * 色の圧縮(高度)
             */
            "colorClampAdvanced": string;
            /**
             * 歪み
             */
            "distort": string;
            /**
             * 二値化
             */
            "threshold": string;
            /**
             * 集中線
             */
            "zoomLines": string;
            /**
             * ストライプ
             */
            "stripe": string;
            /**
             * ポルカドット
             */
            "polkadot": string;
            /**
             * チェッカー
             */
            "checker": string;
            /**
             * ブロックノイズ
             */
            "blockNoise": string;
            /**
             * ティアリング
             */
            "tearing": string;
            /**
             * 塗りつぶし
             */
            "fill": string;
        };
        "_fxProps": {
            /**
             * 角度
             */
            "angle": string;
            /**
             * サイズ
             */
            "scale": string;
            /**
             * サイズ
             */
            "size": string;
            /**
             * 半径
             */
            "radius": string;
            /**
             * サンプル数
             */
            "samples": string;
            /**
             * 位置
             */
            "offset": string;
            /**
             * 色
             */
            "color": string;
            /**
             * 不透明度
             */
            "opacity": string;
            /**
             * 正規化
             */
            "normalize": string;
            /**
             * 量
             */
            "amount": string;
            /**
             * 明るさ
             */
            "lightness": string;
            /**
             * コントラスト
             */
            "contrast": string;
            /**
             * 色相
             */
            "hue": string;
            /**
             * 輝度
             */
            "brightness": string;
            /**
             * 彩度
             */
            "saturation": string;
            /**
             * 最大値
             */
            "max": string;
            /**
             * 最小値
             */
            "min": string;
            /**
             * 方向
             */
            "direction": string;
            /**
             * 位相
             */
            "phase": string;
            /**
             * 頻度
             */
            "frequency": string;
            /**
             * 強さ
             */
            "strength": string;
            /**
             * ズレ
             */
            "glitchChannelShift": string;
            /**
             * シード値
             */
            "seed": string;
            /**
             * 赤色成分
             */
            "redComponent": string;
            /**
             * 緑色成分
             */
            "greenComponent": string;
            /**
             * 青色成分
             */
            "blueComponent": string;
            /**
             * しきい値
             */
            "threshold": string;
            /**
             * 中心X
             */
            "centerX": string;
            /**
             * 中心Y
             */
            "centerY": string;
            /**
             * 密度
             */
            "density": string;
            /**
             * 線の影の太さ
             */
            "zoomLinesOutlineThickness": string;
            /**
             * 中心径
             */
            "zoomLinesMaskSize": string;
            /**
             * 円形
             */
            "circle": string;
        };
    };
    /**
     * 下書き
     */
    "drafts": string;
    "_drafts": {
        /**
         * 下書きを選択
         */
        "select": string;
        /**
         * 下書きの作成可能数を超えています。
         */
        "cannotCreateDraftAnymore": string;
        /**
         * この内容では下書きを作成できません。
         */
        "cannotCreateDraft": string;
        /**
         * 下書きを削除
         */
        "delete": string;
        /**
         * 下書きを削除しますか？
         */
        "deleteAreYouSure": string;
        /**
         * 下書きはありません
         */
        "noDrafts": string;
        /**
         * {user}への返信
         */
        "replyTo": ParameterizedString<"user">;
        /**
         * {user}のノートへの引用
         */
        "quoteOf": ParameterizedString<"user">;
        /**
         * {channel}への投稿
         */
        "postTo": ParameterizedString<"channel">;
        /**
         * 下書きへ保存
         */
        "saveToDraft": string;
        /**
         * 下書きから復元
         */
        "restoreFromDraft": string;
        /**
         * 復元
         */
        "restore": string;
        /**
         * 下書き一覧
         */
        "listDrafts": string;
        /**
         * 投稿予約
         */
        "schedule": string;
        /**
         * 予約投稿一覧
         */
        "listScheduledNotes": string;
        /**
         * 予約解除
         */
        "cancelSchedule": string;
    };
    /**
     * 二次元コード
     */
    "qr": string;
    "_qr": {
        /**
         * 表示
         */
        "showTabTitle": string;
        /**
         * 読み取る
         */
        "readTabTitle": string;
        /**
         * {name} {acct}
         */
        "shareTitle": ParameterizedString<"name" | "acct">;
        /**
         * Fediverseで私をフォローしてください！
         */
        "shareText": string;
        /**
         * カメラを選択
         */
        "chooseCamera": string;
        /**
         * ライト選択不可
         */
        "cannotToggleFlash": string;
        /**
         * ライトをオンにする
         */
        "turnOnFlash": string;
        /**
         * ライトをオフにする
         */
        "turnOffFlash": string;
        /**
         * コードリーダーを再開
         */
        "startQr": string;
        /**
         * コードリーダーを停止
         */
        "stopQr": string;
        /**
         * QRコードが見つかりません
         */
        "noQrCodeFound": string;
        /**
         * 端末の画像をスキャン
         */
        "scanFile": string;
        /**
         * テキスト
         */
        "raw": string;
        /**
         * MFM
         */
        "mfm": string;
    };
}
