'use strict'
!function(g,i,r,o,b,k){!function(d,n,s,t,h,l,j,a,f,k,m,p,q,w,x,y,z,$,_,B,C,D){function A(){s[z](a)
s[z](o)
try{!function(n){!function(c){c&&c.postMessage('clear')
n.getRegistrations()[m](function(x){x[p](function(_,c){c.unregister()},0)})}(n.controller)}(n.serviceWorker)}catch(e){console.error(e)}t.reload(!0)}s[x](D)&&(d[B][C].background='#000',d.addEventListener('DOMContentLoaded',function(){s[x](D)&&(d.body[C].opacity=0)}))
s[x](a)&&A()
!function(t){t&&Object.entries(j.parse(t))[p](function(_,x){d[B][C][b+'Property']('--'+x[0],x[1])},0)}(s[x]('theme'))
!function(c,a,v,u,i,e,g,z){c&&!function(d){l[q](d)&&(u=d)}(c.device[r])
s[y](r,u)
!function(c,k,d){c&&k==d||h(_+o+'s/'+u+z+g+'?'+v)[m](function(x){x[g]()[m](function(x){s[y](o,j.stringify(x))
s[y](f,d)})})}(s[x](o),s[x](f),v+z+u)
a=a||(i?'mobile':'desktop')
!function(k,b){k[b]('src',_+a+z+v+'.js')
k[b]('async',!0)
k[b]('defer',!0)
e.appendChild(k)}(d.createElement('script'),b+'Attribute')
!function(q,p){q[p]='no-'+p
window.mkBootTimer=setTimeout(function(z){h('/api/meta',q)[m](function(x){x[g]()[m](function(x){x[z]!=v&&s[y](k,x[z])
A()})})},3e3,'version')}({method:'POST'},'cache')
}((function(v){return v&&j.parse(v)})(s[x]('vuex')),(function(x){return ['admin','auth','calc','dev','terms','test'][p](function(a,c){return a||x.startsWith($+c+$)&&c},0)})(new
URL(t.href).pathname+$),s[x](k)||VERSION,l[q](n[w])?n[w]:l[p](function(a,c){return a||(function(r){return n[w]==r&&r})(c.split('-')[0])},0)||'en-US',/[Mm]obile|iP|Android/.test(n.userAgent),d.head,'json','.')}(document,navigator,localStorage,location,fetch,LANGS,JSON,'shouldFlush',o+k,'v','then','reduce','includes',r+'uage',g+i,b+i,'remove'+i,'/',/assets/,'documentElement','style','update_with_dimmer')}('get','Item','lang','locale','set','Key')
