name: Merge upstream branches

on:
  push:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name ${NAME}
          git config --global user.email ${EMAIL}
          git config --global pull.rebase merges
          git pull
          git remote add upstream ${REPO_FORK}
          git fetch upstream
          GIT_HASH=`git rev-parse upstream/develop`
          echo ${GIT_HASH}
          git merge -Xtheirs --no-edit --allow-unrelated-histories upstream/develop && git checkout . && git add . && git commit || echo "No changes to commit"
          BASE_VERSION=`npm version | grep -Po -m1 "(?<=')[^',]+(?=-)" || npm version | grep -Po -m1 "(?<=')[^',]+(?=')"`
          echo ${BASE_VERSION}
          npm version "${BASE_VERSION}-$(echo ${GIT_HASH} | cut -c1-7)" || echo "Version not changed"
          git push origin develop
        env:
          NAME: nokotaro
          EMAIL: takenoko@mail.nokotaro.com
          REPO_FORK: https://github.com/misskey-dev/misskey.git
