name: Merge upstream branches

on:
  push:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name ${NAME}
          git config --global user.email ${EMAIL}
          git config --global pull.rebase merges
          git pull
          GIT_HASH_OLD=$(cat package.json | jq -r '.version' | grep -Po '[a-z0-9]{7}$')
          echo $GIT_HASH_OLD
          git remote add upstream ${REPO_FORK}
          git fetch upstream
          GIT_HASH=$(git rev-parse upstream/develop | cut -c1-7)
          echo $GIT_HASH
          [ "$GIT_HASH" != "$GIT_HASH_OLD" ] && git merge -Xtheirs --no-edit --allow-unrelated-histories upstream/develop && git checkout . && git add . && git rebase --continue && git commit || echo "No changes to commit"
          PACKAGE_VERSION=$(cat package.json | jq -r '.version')
          echo $PACKAGE_VERSION
          DATE_AND_TIME=$(date +%Y%m%d%H%M%S)
          echo $DATE_AND_TIME
          [ "$GIT_HASH" != "$GIT_HASH_OLD" ] && npm version "${PACKAGE_VERSION}-${DATE_AND_TIME}.${GIT_HASH}" || echo "Version not changed"
          git pull
          git push origin develop
        env:
          NAME: nokotaro
          EMAIL: takenoko@mail.nokotaro.com
          REPO_FORK: https://github.com/misskey-dev/misskey.git
