name: Merge upstream branches

on:
  push:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name ${NAME}
          git config --global user.email ${EMAIL}
          git config --global pull.rebase merges
          git pull --unshallow
          git remote add upstream ${REPO_FORK}
          git fetch upstream
          git checkout --track origin/develop
          git merge --no-edit upstream/develop
          BASE_VERSION=`npm version | grep -Po -m1 "(?<=')[^',]+(?=-)"`
          npm version ${BASE_VERSION}-$(echo ${GITHUB_SHA} | cut -c1-8)
          git pull
          git push origin develop
        env:
          NAME: nokotaro
          EMAIL: takenoko@mail.nokotaro.com
          REPO_FORK: https://github.com/misskey-dev/misskey.git
